[tool.black]
exclude = "(\\.mypy_cache|node_modules|scss|sql|static)"

[tool.isort]
skip = "alembic"
line_length = 88
multi_line_output = 3  # "Vertical Hanging Indent" style
include_trailing_comma = true
lines_after_imports = 2
known_third_party = "alembic"
order_by_type = false
